services:
  - type: web
    name: saeed-portfolio-website
    env: python
    buildCommand: pip install --upgrade pip && pip install -r requirements.txt
    startCommand: gunicorn main:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.12
      - key: FLASK_ENV
        value: production
      - key: SECRET_KEY_PASS
        generateValue: true
      - key: MAIL_EMAIL
        sync: false
      - key: MAIL_PASSWORD
        sync: false
